### ISSUE TITLE
Provide suggested fixes

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#1]
Suggestion from Collin Winter:

Some analysis tools can not only flag issues, but also suggest potential fixes, which can then be applied by the IDE/code review/code browsing/etc tools. In Google's _Tricorder_, this is represented as a `Fix` object, attached to the equivalent of the SARIF `Issue` object; each `Fix` has a human-readable description and a non-empty list of `Replacement` objects, which simply replace a byte range with some new list of bytes.

**Comment by michaelcfanning** [comment]
This would be useful. Roslyn also provides for code fixes that could be incorporated into the log. Note that the replacement objects could potentially to refer to arbitrary files outside the analysis target/issue file (a type rename, for example, would require fix-ups for all type references).

**Comment by ghost** [comment]
@srivatsn 

Manish and Sri pointed out that if the `Replacement` objects are simple byte ranges, they must be tied to a particular version of the file. Once the file has been changed by somebody else, the fix cannot (in general) be applied any more. Is this acceptable? We have to understand the scenarios in which these suggested fixes would be used.

**Comment by ghost** [comment]
@collinw

I have a draft spec for addressing this issue. Please see: https://github.com/sarif-standard/sarif-spec/blob/master/document/Format.mdk#L847-L1046

Let me know what you think!

**Comment by ghost** [comment]
@gdr-at-ms

**Comment by ghost** [comment]
@michaelcfanning please review Section 4.15, "`fix` object". @srivatsn is concerned that as written, my proposal isn't robust to changes in the file.

**Comment by michaelcfanning** [comment]
@lgolding I have reviewed the fix object and it looks good. we haven't addressed the issue of providing a file hash for the fix, however.

**Comment by ghost** [comment]
@michaelcfanning has a web-based tool that fixes casing problems and attribute values. He'll use that to test this.

**Comment by ghost** [comment]
This is done. @michaelcfanning  FYI
