### ISSUE TITLE
Represent stack locations

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#108]
Real stacks have module/file/function information. Our "stacks" have only file/line/column information (and a message which could repurposed to contain the missing information).

Example:
`xunit.execution.desktop.dll!Xunit.Sdk.TestClassRunner<Xunit.Sdk.IXunitTestCase>.RunTestMethodsAsync() Line 205  C#`

Need:
- module
- fully qualified method name (or other scope, e.g. field initializer)
- file location/code offset from start of function
- message (already have)
- a way to express "external code"/"unresolved frame"

**Comment by lgolding** [comment]
Today a stack is `annotatedCodeLocation[]`.
