### ISSUE TITLE
Add properties/tags to runInfo objects?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#116]
Request from SA infrastructure partner. runInfo is a lightly specified object. Do we provide properties/tags here to put arbitrary content? Should we take a pass at trying to populate this element with useful information?

Two good examples: 
id: log files may need a key that associates the content with a larger automation run, to assist with coalescing results
platform: many automation jobs are repeated by hardware platform

**Comment by ghost** [comment]
@michaelcfanning  I'll add properties/tags and take also a first pass at first-class properties.
