### ISSUE TITLE
Item renames

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#141]
Renames:

'runInfo' -> 'run'
'toolInfo' -> 'tool'
'ruleInfo' -> 'rules'
'invocationInfo' -> 'invocation'

**Comment by ghost** [comment]
@michaelcfanning I think we should do `ruleDescriptor` => `rule`

**Comment by ghost** [comment]
@michaelcfanning Also `fileReference` => `file`

**Comment by ghost** [comment]
@michaelcfanning Also `runStartTime` and `runEndTime` => `startTime` and `endTime`. (These properties are now in an object named `run`, which makes it obvious that the property names don't have to repeat "`run`". It was equally true when the object was named `runInfo`; it's just more obvious now.)
