### ISSUE TITLE
How do we handle response files?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#149]
currently we have a single 'invocation' property. what if the command-line refers to a response file along with other arguments explicitly on the command-line?

**Comment by ghost** [comment]
In v1 we will provide guidance suggesting that the tool place the fully expanded command line in `invocation.parameters`. I'll do that, then assign this to Future milestone for consideration of a more elaborate design, perhaps:

``` json
"invocation": {
  "parameters": "/x /y @a.rsp /a @b.rsp",
  "responseFiles": {
    "a.rsp": { "..." },
    "b.rsp": { "..." }
  }
}
```

**Comment by ghost** [comment]
Could do the same for `configurationFiles` such as `foo.exe.config`.

**Comment by ghost** [comment]
For v1, rename `parameter` to `commandLine`. For future, we consider:
- tools that don't run from the command line
- tools that accept response files
- tools that glob their arguments ("*.cs")
- tools that read configuration files.

Also for v1, recommend using properties for any of this other stuff.

**Comment by ghost** [comment]
Change the spec text.
