### ISSUE TITLE
null value for isSuppressedInSource

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#16]
Why do we offer a choice between null and omitted for tools that don't analyze languages with suppressions, but insist on null for tools that do analyze such languages? Why have null at all?

**Comment by michaelcfanning** [comment]
Seems wrong. I propose that this value is either universally omitted (in circumstances when the information can't be detected) or every issue is explicitly marked 'true' or 'false', as appropriate. @lgolding

**Comment by ghost** [comment]
Changed the spec to say that if the tool _chooses_ to detect this condition, it sets the attribute to `true` or `false`, and if it can't, or chooses not to, or if it is analyzing a language without a "suppress" construct, it omits the attribute.
