### ISSUE TITLE
Providing a JSON schema would be very helpful.

### ISSUE THREAD

**Issue by IObsequious** [sarif-standard/sarif-spec#167]
If you find the time, could you produce a JSON schema to complement the provided document. I am well aware that your standard breaks from JSON at key intervals; however, a rough collection of your SARIF examples or even an attempted JSON schema would be really helpful, but not required. Big fan, by the way, of SARIF!

**Comment by michaelcfanning** [comment]
Hello! We publish the SARIF schema at the link below. The spec is a bit ahead of the current version published here, but we will get everything in sync tomorrow. The Microsoft SARIF sdk (https://github.com/microsoft/sarif-sdk) includes many samples and we're actively working to make sure we have an example of every specified construct (code fixes, rules metadata, etc.). Now that we're close to locking down on v1, we will definitely start producing hand-authored samples that illustrate important concepts.

Thanks for your interest! If you have other requests, let us know. 

http://json.schemastore.org/sarif

**Comment by ghost** [comment]
Yes, thanks @IObsequious.

Could you please clarify where SARIF departs from JSON? It's certainly our goal for it to be fully compliant with JSON (and we read and write it with Newtonsoft's Json.NET), so we weren't aware of any deviations. If there are any, we want to fix them now!

Thanks,
Larry

**Comment by ghost** [comment]
Closing as fixed since we do have a schema as requested, but @IObsequious, feel free to file a separate issue if you have concerns about our level of JSON compliance.

**Comment by IObsequious** [comment]
@lgolding 

I don't really know why I wrote that! It was a late night, I suppose. Disregard, thanks.
