### ISSUE TITLE
Partition results by audience

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#169]
We originally designed the `result` object to represent an observation made by a tool about a programming artifact being analyzed. When we added the `kind` property to result, we allowed it to have the values `error`, `warning`, and `note` as you'd expect. But we also took the opportunity to extend our interpretation of `result` to cover two more scenarios:

| `kind` | Meaning |
| --- | --- |
| `configurationError` | An error occurred while reading rule configuration information |
| `internalError` | The tool encountered an internal error that prevented it from performing a complete analysis (either because of a failure in a rule, or because of a failure in the "engine" that runs the rules). |

We are now reconsidering whether it was wise to use `result` to apply to all three scenarios. There are at least three arguments against doing so:
1. The three kinds of results are intended for different audiences. Results whose `kind` is `error`, `warning`, or `note` are intended for developers who want to know what's wrong with the code they're writing. Results whose `kind` is `configurationError` are intended for build engineers who want to know if they've configured the build correctly. Results whose `kind` is `internalError` are intended for tool authors who want to know what went wrong with their tool at runtime.
2. Severity is orthogonal to audience: Why couldn't there be an item in the log that's just an informational note about your configuration? Why couldn't there be runtime warnings from the tool, instead of just errors?
3. Not all fields apply to all audiences: `locations`, `codeFlows`, `stacks`, `relatedLocations`, `fullyQualifiedLogicalName`, and `logicalNameKey` don't apply to configuration issues. You could argue less strongly that they don't apply to tool runtime issues either, although `stacks` might, if the runtime issue resulted in an exception.

In this issue, we'll propose a design that partitions results by audience.

@michaelcfanning @nguerrera @rtaket

**Comment by ghost** [comment]
There are a few arguments against doing this:
1. Uniform viewing: If all three kinds of results are represented in the same way, then viewers (such as the Error List window in Visual Studio) can easily present them all together.
2. We could address orthogonality simply by introducing a property like `audience` with values `developer`, `toolAuthor`, and `buildEngineer` (or alternatively, a property like `category` with values `analysisResult`, `toolInternalResult`, and `configurationResult`), leaving the `kind` property with the remaining values `error`, `warning`, `note`, `pass`, and `notApplicable`. That would be a much less intrusive change than splitting the results into three buckets, and representing each bucket with a different kind of object.
3. So what if fields don't apply? They're optional.

Thoughts?

**Comment by michaelcfanning** [comment]
These points are credible but ultimately, I'm not sure I find them persuasive. For point 1, most consumers will want to focus on the data that is highest priority for them, so organizing as distinct buckets makes sense. Yes, a really great viewer might want to show all this data but I think we agree that most viewers would want to start with showing the successfully produced tool results. Despite marking things as optional, people make assumptions about what data is there (such as the analysis target location), since that's the bread-and-butter information. Viewers that treat this data in a uniform way will be in for a surprise when they encounter the first tool exception (that has no analysis target or result file). This was our own experience in VS (it turns out we have no model/UX for showing these results at all and so they must be excluded pending more work).

In re: #2, I don't think we'll work ourselves into a cleaner situation by proposing additional attributes that need to be inspected.

**Comment by ghost** [comment]
I think I ultimately agree with you because of this: "Viewers ... will be in for a surprise when they encounter the first tool exception (that has no analysis target...)".

As to #1, I agree that most consumers want to _focus_ on the analysis results, but they sure as heck want to _know_ if the tool failed, so being able to put that information right in their face is a good thing. But, as you say, a clever enough viewer can synthesize an Error List item from a tool failure it it wants to.

**Comment by michaelcfanning** [comment]
ultimately, we want to get results to the right audience (a tool owner, a tool runner, a tool user). the current mechanism makes these distinctions non-obvious. the current mechanism makes audience explicit in some cases ('internalError') and not others 'note). that argues for separating the data. all things considered, I think the advantages of doing so are worth the changes required to process logs.

**Comment by ghost** [comment]
Proposal:
1. Remove the values `pass`, `notApplicable`, `configurationError`, and `internalError` from the `kind` enumeration, leaving only `error`, `warning`, and `note`.
2. Rename the `kind` enumeration to `severity`.
3. Rename the `result.kind` property to `result.severity`.
4. Add two more properties to the `result` object:
   - `toolRuntimeIssues` (optional; type: `toolIssue`)
   - `toolConfigurationIssues` (optional; type: `toolIssue`)
5. Each of these is an array of a newly defined object `toolIssue`, with these properties:
   - `message` (required, type: `string`)
   - `severity` (optional; type: `severity`)
   - `tags` (optional; type: `tagSet`)
   - `properties` (optional; type: `propertyBag`)
   - `exception` (optional; type: `exception`)
6. The `exception` object has these properties:
   - `type` (required; type: `string`): The FQLN type name of the exception, _e.g._, `System.ArgumentException` or `std::runtime_error`.
   - `message` (required; type: `string`)
   - `stack` (optional; type: `stack`)
   - `innerException` (optional; type: `exception`)
   - `tags` (optional; type: tagSet)
   - `properties` (optional; type: `propertyBag`)
   
   Note: I don't propose an `HRESULT` or similar property. I don't think it deserves to be first-class. .NET-based tools can put it in the property bag if they want.

**Comment by michaelcfanning** [comment]
1) can we find a term other than severity. how does 'level' work for you?
2) you 100% certain about the exception nesting? if so, innerException needs to be innerExceptions for aggregating exception types
3) just a question, the 'exception' type could, in theory, be useful in the results section at some future point, right? (such as a runtime tool that is logging them).
4) need more thinking on names. A toolConfigurationIssue is a kind of runtime issue. how about just getting back to the basics, internalErrors and configurationErrors? mostly, we expect these to only be populated with errors. in verbose reporting environments, other content could be there, but the primary purpose is for this content (catastrophic/run-impacing tool and/or config problems).

**Comment by ghost** [comment]
1) Why? "Severity" is so commonly used.

2) Not certain. I did think of that, but I didn't want to promote .NET `AggregateException` to a position of prominence in the format. I suppose such a thing could occur elsewhere (although a web search for "aggregate exception" turns up nothing else). OK, I'll make it an array. Doesn't hurt.

3) Absolutely. I considered adding it to `result` to handle the case where a dynamic tool encounters an exception in the course of executing the target. I didn't propose it for v1 because I didn't want to have to think about the relationship between the stack in `result.exception.stack` and the stacks in `result.stacks`. Does a viewer have to look in both when displaying stacks? Can the same stack occur in both places? I filed #171, "Should result have an exception property?" with Milestone=Future.

4) We can think about it some more; I'm open to being persuaded. Right now I'm reluctant to name something "XxxErrors" if it can contain things that aren't errors. And the existing names work nicely with the name of the object type `toolIssue`.

**Comment by ghost** [comment]
But I do see why you consider them both "runtime" errors. How about `toolInternalIssues` and `toolConfigurationIssues`?

**Comment by ghost** [comment]
We settled as follows:
1. `severity` => `level` (because it includes things like `notApplicable` that don't "feel" like a severity).
2. `notification.exceptions` is now an array.
3. `result.exception` deferred to vNext.
4. Settled on names `toolNotifications` and `configurationNotifications`, with both being arrays of `notification` objects.
