### ISSUE TITLE
identical member names that resolve to different types

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#179]
result.locations is an array of 'location' objects.
codeFlow.locations is an array of 'annotatedCodeLocations'.

notification.level 
result.level

These are two places in the spec where members with identical names resolve to different types. Just putting this fact forward for review. Are we ok with this?

**Comment by ghost** [comment]
I'd be ok renaming them `codeFlow.annotatedLocations`, `notification.notificationLevel`, and `result.resultLevel`, but is Nick checked in?

**Comment by ghost** [comment]
After discussion with @michaelcfanning: We're leaving it as is.
