### ISSUE TITLE
Can we specify a reasonable set of values for logicalLocation.kind, or is it a free-for-all?

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#19]
Prescribing a fixed list at this point would be a breaking change.

**Comment by ghost** [comment]
Implementing converter for FxCop project file may illuminate this.

**Comment by ghost** [comment]
We might provide a set of locationKind values per-target-language: Were we scanning C, Java, SQL?

The requirement for formatSpecifiers is that they be per-consuming-tool: Is the tool capable of scanning C format strings?

**Comment by ghost** [comment]
Answer: we specified a small set of recommended values, but allowed anything else if none of them was appropriate.

**Comment by michaelcfanning** [comment]
SDK Schema diverges from spec. What's correct? Here's the spec:

function 
member 
method 
module 
namespace 
package 
resource 
type 

Here's the schema description. We definitely eliminated 'declaration'. It looks as though we favored reducing things to the most general class. So we have 'type' (without allowing to distinguish between 'class' and 'struct'. By this measure we would get rid of 'method' as a kind of managed 'member'. So I think that's what I would suggest (remove 'method', leaving 'function' for the native world). And remove 'declaration' from the schema text. ?

'declaration', 'function', 'member', 'module', 'namespace', 'package', 'resource', or 'type'

**Comment by ghost** [comment]
Yes, we eliminated declaration and should remove it from schema text. Yes, we reduced class/struct to "type".

IIRC we explicitly kept "method" because we felt it was useful to distinguish methods from all other kinds of members. But we'll remove it for now.

Re: "function": the distinction here isn't between managed and native; it's between "free function" and "function that's a member of a class". C++ has both methods and functions and I think it's worth keeping both.

**Comment by ghost** [comment]
@michaelcfanning This is now settled.
