### ISSUE TITLE
Region object too complicated

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#2]
Collin Winter wrote:

I'm concerned about the number of possible configurations for the `region` objects. At Google, we initially allowed analysis tools to specify locations as either text ranges or byte ranges, with text ranges having several permutations. The goal was to make it as easy as possible for analysis authors to specify locations. However, the number of different configurations this allowed, crossed with the growing number of tools that have ended up consuming these objects, has caused quite a number of bugs over the years. Today, we are working to standardize on byte ranges, which all our tools can produce, as a single, simple interchange with only a single valid configuration (starting and ending byte offsets).

**Comment by michaelcfanning** [comment]
The flexibility here is to accommodate conversion of numerous tool outputs that use line/column information. Minimally, we should make a clear recommendation in the standard for tools that are providing direct support (which could be start/end byte offsets as Collin suggests).

One thing to look at, though, is how this would impact tools that provide many line locations for reporting (to describe a presumed path through a function, etc.).

**Comment by ghost** [comment]
What Michael wrote is fine, but to be even _more_ explicit: We want the format to support two scenarios:
1. A tool natively emits the SARIF format.
2. A tool emits its own custom format, and we want to convert it to SARIF so that the tool can participate in all SARIF-based workflows.

In scenario 2, we don't have the information we need to convert the line/column that the tool produces into a byte offset (we don't know the length of each line, and we don't know the encoding of the original file). So SARIF has to support line/column-based locations for the sake of these tools.

Collin, does that make sense?

**Comment by michaelcfanning** [comment]
I'd be interested to hear more about text range permutations you supported and the bugs you encountered. :)

**Comment by ghost** [comment]
We're going to leave this as is for v1 (+/- various tweaks mentioned in #132).
