### ISSUE TITLE
why is fix description required? can a fix not be self-evident in preview?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#211]

**Comment by ghost** [comment]
@michaelcfanning  I've argued consistently to keep the requirement so UI's like the Roslyn fixer UI have something to show. Did we close on this?

**Comment by michaelcfanning** [comment]
yes, I think so. the description is useful for the reason you cite. also, since we require encoding the fix, the description is helpful to log readers to understand the proposed change, otherwise it is entirely opaque.

**Comment by michaelcfanning** [comment]
iow, agree, let's close this by design.

**Comment by ghost** [comment]
Perfect.
