### ISSUE TITLE
Should 'snippet' be on the physicalLocation?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#217]
Only if we expect the snippet to conform to the region of a physical location. If we don't expect this, should items other than 'result' have a snippet property? e.g., 'relatedLocations'.

Michael

**Comment by ghost** [comment]
@michaelcfanning Let's consider for Future.

**Comment by michaelcfanning** [comment]
let's make a call. nothing has shipped that produces this. so what's the call?

**Comment by michaelcfanning** [comment]
based on previous discussion, I tend to think we are tending towards zapping physicalLocation rather than augmenting it. so, would tend to think that 'snippet' would stay where it is on result and that we'd add a 'snippet' item to annotatedCodeLocation if we see demand for it.

**Comment by ghost** [comment]
I agree with your reasoning that `result` is better than `physicalLocation` (and we can add it elsewhere in future if needed). But... if no tool or converter produces snippets today, shouldn't we remove them from the spec and schema entirely, on the principle that we shouldn't ship something we haven't exercised?

**Comment by ghost** [comment]
The answer to the question posed by the issue title is "No". Per our discussion, `snippet` stays on `result`, and in future we can add it elsewhere.

Here's an example of what we have today (emitted by **ModernCop**):

```
        {
          "ruleKey": "JS2074.IdentifierNameIsMisspelled",
          "level": "error",
          "formattedRuleMessage": {
            "formatId": "Default",
            "arguments": [
              "args",
              "parameter",
              "args"
            ]
          },
          "locations": [
            {
              "analysisTarget": {
                "uri": "file:///d:/src/SecDevTools/Main/src/ModernCop/Source/Mod50.Test.Unit/ModernCopTestData/Mod50/CompiledPackages/SimpleJSApp.appxbundle#/SimpleJSApp_1.0.0.1_AnyCPU.appx/pages/section/section.js",
                "region": {
                  "startLine": 46,
                  "startColumn": 23,
                  "endLine": 49,
                  "endColumn": 10,
                  "offset": 1668,
                  "length": 198
                }
              }
            }
          ],
          "snippet": "function (args) {\r\n            var item = this._items.getAt(args.detail.itemIndex);\r\n            WinJS.Navigation.navigate(\"/pages/item/item.html\", { item: Data.getItemReference(item) });\r\n        }"
        },
```
