### ISSUE TITLE
We need to specify a default value for annotated code location 'essential' property

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#227]
It seems like a default value of 'true' would be most expected. Since adding verbose messages is not the common case. We need to verify the PREfast behavior.

**Comment by michaelcfanning** [comment]
The PREfast converter currently assumes 'false' is the default value. So does the current SARIF serialization logic.

**Comment by michaelcfanning** [comment]
So PREfast does the same thing, emits 'essential' only when the value is true. I think this is wrong, because in the case when essential == false is never a possibility (for loggers that don't interleave verbose steps), the logger needs to constantly emit essential == true. Ship has sailed, though. Can we add something to 1.1 to revisit this behavior?

**Comment by michaelcfanning** [comment]
@lgolding, this is resolved, yes? we now have an 'importance' property. the default is 'important', other possible values are 'unimportant' and 'essential'

**Comment by ghost** [comment]
@michaelcfanning Yes.
