### ISSUE TITLE
annotatedCodeLocation requires physicalLocation...

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#228]
In one tool (the Static Driver Verifier), we see some verbose messages that are interleaved with the code flow that do not have a location. these messages need to provide a bogus physical location, currently, due to requirement to have a physicalLocation.

**Comment by michaelcfanning** [comment]
@lgolding, did you see this? I think we need to eliminate the requirement for ACLs to have a location, not a breaking change. Do you agree?

**Comment by ghost** [comment]
Not sure. Please show me the example. Maybe there's another way to structure this that doesn't require us to allow aCLs without a location.

**Comment by ghost** [comment]
@michaelcfanning Please see my response above. I'd like to see an example of this. Thanks.

**Comment by ghost** [comment]
OK, I see that the use case is SDV, where the .tt files have lines that look like this:

```
236 "?" 0 true ^====Auto=====^s=1 Atomic Continuation
```

... where the `"?"` means no location is available (or does it? Maybe it just means "the next source line in the same file").

**Comment by ghost** [comment]
From conversation with Jakob, I learned that these "steps-without-a-location" really are execution steps -- they are not, for example, some kind of "messages" interspersed with the "real" steps -- they're just steps whose location we don't happen to know. So yes,I agree with your original suggestion, that `annotatedLocation.physicalLocation` be made optional.
