### ISSUE TITLE
Execution flow entries should be able to express arbitrary events

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#24]
An execution flow entry should be able to express events that were observed or presumed during execution. Currently, these would be expressed as an executionFlowEntry object (potentially with no associated physicalLocations) that describe event details in the message property. Is this sufficient?

**Comment by ghost** [comment]
@michaelcfanning An execution flow now consists of an array of `annotatedCodeLocation` objects, each of which can have a `message`, `tags`, and `properties`. I think this suffices. Please let me know if you agree.

**Comment by michaelcfanning** [comment]
Let's finish the tool result converters that produce this data and if no new issues turn up, we can close. I've added 'prototype-needed' to this issue.

**Comment by ghost** [comment]
Do you want to point me at one of those partially-finished converters, and the input format it accepts, and I'll do that?

**Comment by ghost** [comment]
For purposes of this issue ("arbitrary stuff"), tags and properties suffice. #24 is about whether we need more "specific stuff". That one's still open.
