### ISSUE TITLE
Should messageFormats be able to refer to result properties?

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#244]
For example:

```
"This is bad because {properties.reason}. The level is {level}."
```

... would refer to `result.properties.reason` and `result.level` from the current `result` object.

@tikiwan @michaelcfanning

**Comment by TikiWan** [comment]
Here are my 2 cents
   -- There are two types of user whom will consume SARIF
          -- Computer
                  -- Need to access information from a define property, so, there is no string parsing needed
          -- Human
                 -- Who read the output message and trying to make sense of it

Without this feature, most of the information in the output message will need to be duplicate into a more define property for the tool owner to satisfy both type of users.

**Comment by ghost** [comment]
I agree. Most of the time, you don't need the `result.formattedRuleMessage` feature at all. You can get away with a generic `result.message` like `"; expected"`. But whenever you do need to format additional information into the message, it is possible that you'll want a computer to be able to access the information.

**Comment by michaelcfanning** [comment]
I'm not sure this is a good idea. Rule messages shouldn't be injecting things like 'level', they should stick to the message. Otherwise, we end up with redundant output like : ERROR: this is a message. it is an error.

The current mechanism (provide your args as args) is arguably sufficient. What this feature buys us is the ability to provide an argument name that is an opportunity to be more descriptive about what an argument represents (I agree this is a value). On the other hand, how do we handle localization in this case? i.e., will we have to translate the property names? that seems a little burdensome. 

Do we foresee that this proposal introduces any additional parsing burdens for consumers building completely formatted messages? For example, we'd now probably need to prohibit introducing braces into property bag key names, yes?

**Comment by ghost** [comment]
I'll go so far as to agree with you that it's not necessary to inject anything that's a first class property, like `level`. But property bag properties could be valuable, because viewers would have no knowledge of them (except that I suppose a viewer could dump the whole property bag).

Yes, you're right, we'd need to restrict property bag names. (I don't see that as a deal-breaker for this feature, but it's a good point.)

**Comment by TikiWan** [comment]
Michael bring up a very good point about localization. Are we planning to only support the formatted messages? Or we will support all first class string property as well? Or it is up to the consumer app?

One concern of not supporting this feature is that we will end up having a lot of duplication information inside SARIF, and the size of the SARIF file become too big.

**Comment by ghost** [comment]
@TikiWan: Are you asking whether I was proposing to support the existing substitution syntax `{0}`, and also the extended substitution syntax `{propertyName}`, anywhere _except_ in `formattedMessage`? If so, the answer is no: the existing syntax is only supported for `formattedMessage`, and the extended syntax also would be supported only for `formattedMessage`.

The answer to the question "Which properties are allowed to use the substitution syntax?" can't be up to the application that consumes the log file; it has to be specified in the spec. Any first class property that makes use of the substitution syntax would have to be accompanied by an array-valued `arguments` property that would hold the values for the placeholders. There is only one such property in the spec (`formattedMessage.arguments`).

@michaelcfanning: I was not proposing this as a means of making the un-substituted value of `formattedMessage` more readable; I was proposing it as a means of reducing repetition in the log file. So localization of the property names isn't an issue.

@TikiWan Although log file size is certainly a concern (and we've gone to considerable effort to reduce it; see, for example, the `run.files` property and the `run.logicalLocations` property) I don't think it's a big concern in this case. A few extra short strings per `result` object is small, compared with the size of the `result` object as a whole -- especially if the `result` objects include `codeFlows` (which in PREfast and SDV output completely dominates the size of the log file).

Having said all of that -- it was an interesting idea, and nothing we've discussed so far seems like a deal-breaker to me. But I don't feel strongly enough about it to actually put it on the backlog to implement. I'm willing to drop it.

**Comment by TikiWan** [comment]
I agree. We can use V1 for a while and we can only fix issues when we have real data support it.

**Comment by ghost** [comment]
Very good! Thanks for the discussion.
