### ISSUE TITLE
Enhance aCL for other "kinds"

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#249]
When `annotatedCallLocation.kind` is `call`, we have the `callee` property to specify the target of the call. @michaelcfanning has suggested similar properties for other `kind` values. Michael, what do you think of these:
- An `assignee` property to hold the variable being assigned when `kind` is `assignment`.
- A `declarator` property to hold the item being declared when `kind` is `declaration`.
- A `function` property to hold the function name when `kind` is `functionEnter` or `functionExit`.

**Comment by michaelcfanning** [comment]
I think the latter two bullets are covered by fullyQualifiedLogicalName.

Put a bit of thought into this and I think we might be able to get away with declaring two new members, only: parameters and variables. Parameters would be used by anything that is parameterized, this includes a call or functionEnter (but also potentially a source, sink or sanitizer, depending).

'variables' would simply be key-value pairs of the same concept, that could be used where appropriate. in a continuation ACL, 'variables' might track a static variable that is assumed to change value. 'variables' could be used in a conditional ACL to indicate specific values of variables relevant to conditional evaluation.

by providing these general things (an unnamed, ordered array of values, and a collection of key/name pairs), we allow tools to be flexible about emitting the data in a way that works for them. consider this assignment:

var test = flag1 & flag2;.

depending on a tool's behavior, it could 'parameterize' this assignment by providing an array with a single value, 'false' (which means 'test' is assumed to have received a value of false). a different tool might populate variables with {flag1 : true, flag2: false) and give a different, richer view into the assignment.

To resummarize, at this point, I think that leveraging the FQLN fully (we should document clearly what FQLN refers to for each ACL kind), parameters and variables, we might be covered. Note that stackFrame provides a parameters member, btw, which argues for using that name,

**Comment by ghost** [comment]
Proposal:
- Add `variables`, `parameters`, and `target`.
- The usage of each of these differs according to `acl.kind`.
- Drop `callee` (use `target` instead).
- Provide matching `call`, `callReturn`; `funcEnter`,  `funcExit` (might not have a location).
- Add `funcReturn` (the actual return statement).
- Explain requirement for matched pairs, unless trace terminates in a nested call.

**Comment by ghost** [comment]
Only breaks SDV.

**Comment by michaelcfanning** [comment]
SDK updated for this change at https://github.com/Microsoft/sarif-sdk/pull/495
