### ISSUE TITLE
Do we require that call/callReturn and functionEnter/functionExit be emitted as matched pairs?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#250]
It is not burdensome to require this for call/callReturn pairs, certainly. You could imagine a codeFlow that occurs within a single method/function, which might make overtly argue for functionEnter.

I think it's probably most straightforward to require they be emitted as matched but we could find that this makes it difficult or impossible to provide converters for some tools (that don't follow the discipline).

**Comment by ghost** [comment]
Answer: Yes, unless trace terminates in a nested call.

The answer to this is included inM #249, "Enhance aCL for other 'kinds'".
