### ISSUE TITLE
should result have an optional timestamp?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#253]
generally, per-result timestamps don't appear to make much sense. arguably, they provide an ordering mechanism (but they could also simply be sorted by the tool explicitly). timestamps introduce non-determinism in files. also, the value of emitting a timestamp with a result is arguably not high, as it only tells when a result fires (i.e., doesn't provide meaningful information about the length of any specific operation, as the explicit timestamp can't be correlated to other analysis which might not have fired).

we have timestamps on invocation (start and end) and notifications (where that information may be important for troubleshooting). I tend to think we don't need/want it on results but it's worth discussing.

**Comment by ghost** [comment]
Per discussion with @michaelcfanning: makes sense for notifications (run start, run end), but not for results.
