### ISSUE TITLE
Organizing SARIF spec into core format + profiles

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#29]
It has become clear through discussions both in person and through the GitHub issues list for this spec that SARIF can serve multiple purposes, in multiple scenarios. For example, it can:
-  serve as a tool output format, carrying information about individual issues detected by a tool.
-  contribute to corporate policy compliance (in particular, auditability) by carrying information about exactly which version of a tool was run, with exactly which options, on exactly which set of files.
-  participate in issue management systems, by carrying information about the triage status of an issue, links to similar issues, comments from developers, and so forth.

In future, we might discover more uses for SARIF, each with slightly different requirements, each requiring a variation on the basic format.

This variety of uses has two consequences for readers and implementers of the SARIF specification:
-   It makes the spec difficult to read, because it contains information that only makes sense to certain classes of readers (for example, tool vendor or corporate policy compliance specialists).
-   It makes the spec difficult to implement, because it is not clear which portions of the spec a particular implementer must support. It's not good enough that the spec says (in ISO-speak) that the format "shall" contain this property or that it "may" contain that property. Implementers need more context to understand _when_ and _why_ they should support a particular property.

To address this complexity, we will divide the SARIF standard into a _core format_ and a set of domain-specific _profiles_. The core format is the basic format that static analysis tools emit. Initially, the spec will define two profiles in addition to the core format:
-   The _issue management profile_, which includes information such as the triage status of an issue.
-   The _policy compliance profile_, which includes information needed to ensure compliance with policies. An example of such a policy is Microsoft's Security Development Lifecycle.

Future profiles might be introduced either as new versions of the SARIF spec, or as independent specs that cite SARIF as a normative reference.

Please let us know if this organization makes sense to you.

**Comment by gdr-at-ms** [comment]
Sounds good!

**Comment by codecurmudgeon** [comment]
Would it make sense to have some kind of "this applies to
consumer/producer" for various sections or properties?

On Tue, Sep 1, 2015 at 4:09 PM, Larry Golding notifications@github.com
wrote:

> It has become clear through discussions both in person and through the
> GitHub issues list for this spec that SARIF can serve multiple purposes, in
> multiple scenarios. For example, it can:
> 
>    -
> 
>    serve as a tool output format, carrying information about individual
>    issues detected by a tool.
>    -
> 
>    contribute to corporate policy compliance (in particular,
>    auditability) by carrying information about exactly which version of a tool
>    was run, with exactly which options, on exactly which set of files.
>    -
> 
>    participate in issue management systems, by carrying information about
>    the triage status of an issue, links to similar issues, comments from
>    developers, and so forth.
> 
> In future, we might discover more uses for SARIF, each with slightly
> different requirements, each requiring a variation on the basic format.
> 
> This variety of uses has two consequences for readers and implementers of
> the SARIF specification:
> 
>    -
> 
>    It makes the spec difficult to read, because it contains information
>    that only makes sense to certain classes of readers (for example, tool
>    vendor or corporate policy compliance specialists).
>    -
> 
>    It makes the spec difficult to implement, because it is not clear
>    which portions of the spec a particular implementer must support. It's not
>    good enough that the spec says (in ISO-speak) that the format "shall"
>    contain this property or that it "may" contain that property. Implementers
>    need more context to understand _when_ and _why_ they should support a
>    particular property.
> 
> To address this complexity, we will divide the SARIF standard into a _core
> format_ and a set of domain-specific _profiles_. The core format is the
> basic format that static analysis tools emit. Initially, the spec will
> define two profiles in addition to the core format:
> 
>    -
> 
>    The _issue management profile_, which includes information such as the
>    triage status of an issue.
>    -
> 
>    The _policy compliance profile_, which includes information needed to
>    ensure compliance with policies. An example of such a policy is Microsoft's
>    Security Development Lifecycle.
> 
> Future profiles might be introduced either as new versions of the SARIF
> spec, or as independent specs that cite SARIF as a normative reference.
> 
> Please let us know if this organization makes sense to you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sarif-standard/sarif-spec/issues/29.

## 

Regards,

Arthur "Code Curmudgeon" Hicken
Office: 626-275-2445 (Los Angeles)
Cell: 909-343-0936
Google voice: 978-49-OWASP (in theory rings my mobile and my desk... in
theory)

**Comment by ghost** [comment]
@codecurmudgeon Hi Arthur, I'm sorry I didn't see your note until now. I think specifying consumer/producer makes alot of sense for the various sections ("profiles"). By design, the objects and properties within each profile would have a common set of producers and consumers, so I don't think I'd do it at that level.

I filed #48 to track this request.

Thanks,
Larry

@michaelcfanning FYI

**Comment by ghost** [comment]
This is now done.
