### ISSUE TITLE
Not all analyses are command-line driven

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#3]
Suggestion from Jeffrey van Gogh

Section 4.6 ("`runInfo` object") assumes that all tools are command-line driven, but some analyses run as services. Allow `runInfo` to optionally represent the service's configuration with some sort of "analysis context" object, instead of restricting it to a string-valued `commandLineArguments` property.

**Comment by michaelcfanning** [comment]
Yes. analysis context could be a good term. we could refer to the run parameterization perhaps. but this should definitely be generalized for non-command-line executions.
