### ISSUE TITLE
commandLineArguments might contain absolute paths

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#33]
This is a privacy concern.

**Comment by michaelcfanning** [comment]
Yes, but it is hard to know what to do about it except to eliminate the information altogether, which may not be helpful. Generally, a privacy concern of this kind is most applicable to a format (such as a PDB) which is intended to have a user-facing application(e.g. debugging, where embedded paths may be visible to 3rd parties who are queried for file locations). The SARIF format does not necessarily fall into category.

We have a better story around file references, where we define a mechanism for eliding enlistment root details (preserving source-control information required to retrieve a file).

My opinion here is that resolving this issue will be mostly a documentation profile. I.E., we will create an appendix around security/privacy-related issues (both from the production and consumption perspective) in a special appendix.

**Comment by ghost** [comment]
@michaelcfanning This is fixed, right?

**Comment by michaelcfanning** [comment]
yes, the matter around commandLineArguments (now invocationContext) is settled.

**Comment by ghost** [comment]
@michaelcfanning (doing a scrub of all issues right now)

I think the original fix was to add text that warned of the danger; then more recently we added the guidance to add the "`[REMOVED]`" token. In any case, this is taken care of.
