### ISSUE TITLE
Provide examples of valid SARIF files

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#35]
Our spec is detailed and complex. We should try to isolate the most critical information for core scenarios. Minimally, we need a minimal valid log file example.

**Comment by michaelcfanning** [comment]
{
  "version": "0.4",
  "runLogs": [
    {
      "toolInfo": {
        "name": "ExampleTool"
      },
      "results": []
    }
  ]
}

**Comment by michaelcfanning** [comment]
@lgolding minimal file example. sorry for losing the formatting.

**Comment by michaelcfanning** [comment]
{
  "version": "0.4",
  "runLogs": [
    {
      "toolInfo": {
        "name": "ExampleTool"
      },
      "results": [
        {
          "ruleId": "ID1001",
          "fullMessage": "'example_analysis_target.exe' does not appear to be a valid portable executable or is corrupted. As a result, it might not execute. Recompile this binary (or ignore this message if this file isn't a portable executable, despite its file extension).",
          "locations": [
            {
              "analysisTarget": [
                {
                  "uri": "file:///C:/build/example_analysis_target.exe"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

**Comment by michaelcfanning** [comment]
Second example is minimal valid file that has at least one analysis result emitted to the log.

**Comment by ghost** [comment]
Per @michaelcfanning: Supply four samples:
1. absolute minimal valid file,
2. minimal file that persists results only, i.e., doesn’t have rules/files/other sibling metadata,
3. ‘mature’ sarif that documents all files and rules,
4. the ‘everything’ file that populates every possible construct in the spec.
