### ISSUE TITLE
how do we designate related items?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#38]
Do we need a mechanism to indicate that two outputs are related? Some tools produce results that chain messages together (either for diagnostic reasons, to provide other code locations of interesting or to assist resolving a result, by emitting helpful out that can assist in resolving a problem).

Some (most?) of these scenarios are arguably resolvable by using the executionFlows property (i.e., for additional output that doesn't actually comprise a distinct result, log authors can add an executionFlow with a location and a message). An issue here is that it isn't clear how viewers can handle these values in a general way.

We could consider adding a property 'relatesToPrevious; that indicates a result is closely tied to the previous result in the log file and should always follow it, no matter how the log is sorted. Log processing tools that persist results to some other store, such as a database, should link these results together (by using an emitted id or something similar).

I'm not 100% we need a fix here. Possible actions (which are exclusive of each other)
1) provide 'relatedToPrevious' field and be done 
2) attempt to use executionFlowEntries for this scenario, possibly generalizing language for the property
3) provide some sort of related results child for an issue which is intended to hold a bundle of additional output, as 'results', that aren't themselves actual issues

**Comment by ghost** [comment]
As we discussed: A note that is related to an issue will be contained within the issue itself, in the new `issue.notes` array.
