### ISSUE TITLE
Rename commandLineArguments to 'parameterization' and remove restriction re: exe

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#42]
I suggest we remove the restriction around eliminating the tool exe name from the parameterization member. i'm not sure what this buys us. it is very helpful in logs to have a completely specified command-line for repeating the analysis (in debugging/lab troubleshooting situations).

if we are concerned about information disclosure in fully-qualified paths, determinism in run-over-run outputs, etc., in output, we should note this in the doc (in a dedicated section that comprehensively documents areas of the format to audit for these concerns, if they are a concern).

related to #3

**Comment by ghost** [comment]
@michaelcfanning This is fixed, right?

**Comment by ghost** [comment]
Yes, confirmed, this is fixed.
