### ISSUE TITLE
Don't require uri for fixes

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#46]
In cases where a fix applies to the immediate analysis target, for which we have a location, we should default to the result uri rather than requiring that it be recapitulated in the fix.

**Comment by michaelcfanning** [comment]
the implied uri, if we take my suggestion, is the uri associated with the analysisTarget member found on the first location in the current result object instance.

**Comment by michaelcfanning** [comment]
@lgolding can you look at this for first release? what do you think?

**Comment by michaelcfanning** [comment]
We're not taking this for now. We will look for additional feedback on the 'fix' elements of the spec from reviewers who proposed them

**Comment by ghost** [comment]
Per @michaelcfanning's comment above, closing this as Deferred.
