### ISSUE TITLE
Tool hashes should not be mandatory

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#6]
Jeffrey van Gogh commented:

Some analyses might not be able to calculate a hash, or the URI might not represent an actual file (_e.g._ a build target).

**Comment by ghost** [comment]
Yes, the spec says "A `fileReference` object **shall** contain a property named `hashes` whose value is an array of `hash` objects..." (my **emphasis**). Instead it should say "should contain".

**Comment by michaelcfanning** [comment]
yes, this is a bug

**Comment by michaelcfanning** [comment]
this issue is now resolved
