### ISSUE TITLE
why is a fix description required?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#61]
6.15.2. description property

Imagine a simple rule 'remove duplicate semicolon at the end of statement'. the fix is to delete the semicolon. do we really require a description here? do we really want duplicated text like 'remove this duplicated semicolon' recapitulated over and over in the log?

I suggest we make this optional and then have the spec note that the description is provided in cases where some supporting text is helpful for users to understand whether or not to apply (or how to understand) the fix. 

Note that Roslyn auto-fixers don't require textual descriptions for fixes. The preview is self-evident in most cases.

**Comment by michaelcfanning** [comment]
@lgolding  please review for v1

**Comment by ghost** [comment]
Can't imagine why it should be required. If a particular tool vendor wants to emit it always, they're welcome to. Don't see why the standard should require it. Go ahead and change "shall" to "may".
