### ISSUE TITLE
make annotatedCodeLocation provide a single physicalLocation only for now

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#62]
The array of locations was proposed to accommodate tools that maintain distinct path information for alternate representations (a tool, for example, that reports against source code but can also report against an intermediate representation that drove analysis, perhaps for debugging purposes).

This scenario is atypical and we haven't tested emitting SARIF for it. In the meantime, the extra layer of indirection in the format is surfacing for all current SARIF providers.

**Comment by michaelcfanning** [comment]
@lgolding please review for v1

**Comment by ghost** [comment]
Fixed by 8d2a5fe.
