### ISSUE TITLE
we do not have a profile member

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#66]
How do SARIF consumers understand whether they are examining a rules info profile-driven representation or an analysis runLog? This distinction is easily expressed in a JSON schema for validation scenarios. For producers/consumers, do we want to provide a hint re: the profile?

This has come up in context of adding a command to binskim to dump all rules metadata. Currently, the spec requires a non-empty array of runLog objects (for the analysis profile). This means we can't generate a SARIF file that simply reports all tool rules and subsequently validate.

**Comment by ghost** [comment]
needs to be an array (enum flags?)

**Comment by ghost** [comment]
"Let it argue its way back in'
