### ISSUE TITLE
consider building out the options object

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#69]
Currently, we specify that options (in the rules metdata profile) refers to a dictionary of key value pairs. The value for this pair is under-specified. Is it a description of the option or something else? We could consider adding default values for options or a regex pattern that validates contents of the option (much as is done in a JSON schema).

**Comment by ghost** [comment]
@michaelcfanning  My intent was that each option represents a configurable value for the rule, for example:

```
// A rule descriptor:
{
  ruleId: "FMT0001",
  name: "LimitLineLength",
  options: [
    "maxLength": "100"
  ]
}
```

**Comment by ghost** [comment]
Not breaking if we keep simple key/string-value pairs; breaking if we change that.

**Comment by ghost** [comment]
Options is gone from v1.
