### ISSUE TITLE
Add link to documentation for issue

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#7]
Jeffrey van Gogh suggested:

It would be great to have a link to documentation/more details associated with the issue. For example, for some analysis around code documentation, we [Google] generate a preview of how the documentation is rendered. It would be nice to have this as rich data instead of the full message.

**Comment by michaelcfanning** [comment]
by discussion, this information should be included in a rules metadata object, not yet defined in the doc
