### ISSUE TITLE
Results member is optional but must be present if a scan actually occurred

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#70]
But in the rules metadata profile, the object of the output is merely to provide a runInfo. For this scenario, there isn't actually any analysis run.

6.3.3. runLogs property

An resultLog object shall contain a property named runLogs whose value is an array of one or more runLog objects (§6.4).

**Comment by michaelcfanning** [comment]
If we don't require a runLog, however, we have no tool-specific information. this points to a larger problem, runLogs can incorporate runs from multiple tools, but ruleInfo aggregates all rules metadata in a single object. I will open a separate issue on this, though it's likely we will need to resolve both at once.
@lgolding

**Comment by ghost** [comment]
As we discussed: `ruleInfo` (which is an array of `ruleDescriptor`) is part of an individual `runLog`, so is associated with a single tool.

**Comment by ghost** [comment]
Ok, re-opening: we're still wrestling with the question of whether it makes sense for there to be a single SARIF format that can contain _either or both_ of:
1. Results from running tools on analysis targets
2. Comprehensive list of rules supported by a tool.

**Comment by michaelcfanning** [comment]
We have decided that the rules metadata scenario makes sense. Now we need to decide where to place rule descriptors. They can be associated with a runLog, since each runLog is associated with a specific tool instance. The run descriptors could also optionally be placed as a member on the toolInfo, since this is tool-specific data.

Alternately, we could distinguish between these locations. runLogs.ruleInfo could, if present, contain format specifier information for messages within the log. toolInfo.ruleInfo could contain an exhaustive set of rule descriptors associated with the tool. The location of this data would clearly indicate something about its completeness. Breaking these apart would increase log file consumer complexity: someone trying to build a formattedMessage would potentially need to examine both locations.

**Comment by ghost** [comment]
We have settled on the current arrangement:

```
runLogs: [
  {
    toolInfo: {}
    runInfo: {}
    results: [
      {
        // a result object
      }
    ],
    ruleInfo: [
        {
          // a ruleDescriptor
        }
    ]
  }
]
```

It correctly associates a set of rules with the tool to which the belong. The only remaining issue is whether to make `results` optional in the "rule metadata" scenario. As the spec stands, it is required, although it may be empty if a run produced no results.

I suggest we change the spec to allow "a run that produces no results" to produce _either_ an empty array _or_ a `null` value for the `results` property. This will save tool authors from having to remember to emit an empty `results` array when the tool is invoked solely for the purpose of producing rule metadata.

@michaelcfanning Let's lock this down.

**Comment by michaelcfanning** [comment]
so you are saying that results must be present but its value could be null? how helpful is this in practice? why don't we just say, if you're emitting the rule metadata profile, ruleInfo is optional?

the only practical implication for us is that we'll require another schema. this could be pretty useful, actually. imagine a compliance-focused schema (that requires hashes). a rules metadata schema. you might want to keep this possibility in mind when authoring your serialization codegen tool (because it potentially introduces complexity)

**Comment by ghost** [comment]
Sorry, I should have said: "either to set the `results` property to an empty array, or to omit it".

Not sure what you mean by suggesting we say "if you're emitting the rule metadata profile, ruleInfo is optional". Did you mean "`results` is optional"?

**Comment by michaelcfanning** [comment]
yes, results is optional

**Comment by ghost** [comment]
but must be present if a scan was run.

**Comment by michaelcfanning** [comment]
yes
