### ISSUE TITLE
byteOffset property typo

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#77]
See all caps CHARACTER below, did you intend use of this term? byteOffset exists in part to permit analyzers to locate issues in binaries that don't relate to text.

6.12.9. byteOffset property

When a region object represents a region in a binary file, it shall contain a property named byteOffset, which shall have an integer value equal to the byte offset of the first CHARACTER in the region from the beginning of the file.

**Comment by ghost** [comment]
You're right, that's a typo. Good catch.
