### ISSUE TITLE
Mention greatest legal value for offset?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#78]
The first, minimal location specified via offset is to set it explicitly to zero and to omit length (because its value is 0). This region is used to indicate an insertion point at the beginning of the file.

The last, legal minimal location that can be expressed is the insertion point at the very end of this file. For this case, offset is set to the length of the file and length is again omitted. Because offset is a zero-indexed value, setting it to the length of the file means this property is outside the range of the file contents and can't be used to index within the file itself. 

This corner case may be worth calling out. Some tools encountered so far do not handle this scenario correctly (i.e., too helpers produce 'index out of range' exceptions for legal regions.

**Comment by ghost** [comment]
We now have only "offset", not "byteOffset" or "charOffset", so I updated the title and description of this issue accordingly.
