### ISSUE TITLE
What's the minimal legal values for regions?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#79]
We should clarify the logic a log consumer goes through to ascertain what sort of region is in hand. For offset-driven regions, we clearly need an explicit charOffset or byteOffset (the length in this case can be omitted, and will have an implied value of 0).

Other than the above, is there any other minimal value requirement? In the absence of an explicit charOffset and byteOffset, we could take implied defaults for startLine and startColumn (of 1). So, the insertion point at the beginning of a text value could be a region with no entries whatsoever.

Or should we require an explicit startLine (and possibly startColumn) for this case?

**Comment by ghost** [comment]
@michaelcfanning The spec has the answer to this:

> The start of a region in a text file shall be represented in one of the following ways:
> - By a combination of the `startLine` and `startColumn` properties. If `startColumn` is not specified, the region is assumed to start at column 1.
> - By means of the `charOffset` property (&sect;[#region-charOffset]),
>   which denotes the offset in characters from the start of the file.

This was meant to imply (although I can certainly add text to clarify it) that if you represent the start of a text file region with a line/column number, then `startLine` is required. You see that the spec allows you to omit `startColumn`, but it doesn't say anything about allowing you to omit `startLine`.

**Comment by michaelcfanning** [comment]
ok. so I believe the answer for SARIF consumers is this: 
1) examine startLine for value >1
2) if it is not, examine charOffset and byteOffset for a non-zero offset. If you find one, this tells you your offset and what unit a non-zero 'length' refers to

this leaves a problematic case for C#, when the offset is zero and length >= 1. for this case, does length refer to a count of bytes or characters? we don't know. if we 'fix' this in C#, we'd need a nullable Boolean type (which are unfortunate to have in an API). another possibility is to make 0 represent an uninitialized value in all cases (i.e., offset would be 1-indexed). not typical for this sort of data. 
thoughts?

**Comment by ghost** [comment]
Pretty much, although it's actually

1) Is startLine > 1?
2) If  not, is startColumn > 1?
3) If not, look for charOffset or byteOffset to tell you what your units are.

I wonder if we should add a boolean or enumerated member to region, regionType (= ByteRegion or CharRegion).

**Comment by ghost** [comment]
Conclusion: Replace `byteOffset` and `charOffset` with `offset` and assume `offset`/`length`-based regions are always in bytes.

Then consumers say:

```
if (startLine > 0 || startColumn > 0)
    // it's a char-based region expressed in lines and columns
else
    // it's a byte-based region expressed as offset and length.
```
