### ISSUE TITLE
Add category/subcategory

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#8]
Jeffrey van Gogh wrote:

Tool + Rule/RuleId seem limiting, in Tricorder we have Category & SubCategory which are orthogonal to the tool that produces them, allowing for implementation to be swapped out. Category and SubCategory are a bit fuzzy but can be considered like this: Category is the kind of analysis you're interested in, e.g. "StringFormatting" and SubCategory is the specific issue found (more like Rule/RuleId in FxCop) e.g. "ConversionMismatch"

**Comment by michaelcfanning** [comment]
we need to add a rules metadata object, as previously discussed, for this sort of thing. the issue ruleId is the key into those details

**Comment by ghost** [comment]
@michaelcfanning 

Resolution: We can use the `tags` property (which didn't exist when this issue was filed) on `ruleDescriptor` to hold one or more categories:

```
tags: [ "security", "globalization" ]
```

We don't see a need for subcategory; "`ruleId`" seems to provide the additional granularity you might need.
