### ISSUE TITLE
Make ExecutionFlow smaller [allow PhysicalLocation to have an array of regions with compact representations]

### ISSUE THREAD

**Issue by ScottLouvau** [sarif-standard/sarif-spec#84]
I was reviewing the ExecutionFlow part of the spec when thinking about representing code coverage data and it would be extremely large to represent. However, if you just allow a PhysicalLocation to contain an array of ranges, you can represent code coverage flows relatively compactly:

For example, consider this trace through a method:
![image](https://cloud.githubusercontent.com/assets/15742033/12310745/cc8b029e-ba06-11e5-91d3-195a40e86ed0.png)

And compare these two JSON representations:
executionFlow:
[
    { uri: “C:\Code\Arriba\Arriba\Diagnostics\ProgressWriter.cs”, startLine: 64, startColumn: 13, endLine: 68, endColumn: 40 },
    { uri: “C:\Code\Arriba\Arriba\Diagnostics\ProgressWriter.cs”, startLine: 71, startColumn: 13, endLine: 75, endColumn: 40 },
    { uri: “C:\Code\Arriba\Arriba\Diagnostics\ProgressWriter.cs”, startLine: 82, startColumn: 13, endLine: 83, endColumn: 43 }
]
[399 bytes]

executionFlow:
[
    { uri: “C:\Code\Arriba\Arriba\Diagnostics\ProgressWriter.cs”, ranges: [ “(64, 13)-(68, 40)”, “(71, 13)-(75, 40)”, “(82, 13)-(83,43)” }
]
[159 bytes]

**Comment by ghost** [comment]
This would be a non-breaking change for producers if we allowed `ranges` alongside the existing properties, and added a constraint that it had to be one or the other. But it would be breaking for consumers, and it has the drawback of defining a mini-language for the `ranges` property, which we've tried to avoid.

**Comment by ghost** [comment]
Won't fix: Rationale: the ranges can be expressed in a variety of ways, which are easy to understand by enumerating the properties, but harder to express in a comprehensible mini-language (unless you restrict producers to emitting ranges that conform to a subset of the spec -- and this is impossible because converters might have any type of range available).
