### ISSUE TITLE
Should ruleId be required? If so, shall we provide guidance on populating if not available?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#96]
ruleId is a key into runInfo data. runInfo data is optional, and most applicable to direct SARIF consumers. For the conversion case, an id may not be available (a tool might simply produce output messages). For this case, a results mgmt system might simply organize its output by tool name and the result kind (error, warning, et al.) if available.

if ruleId remains a required item, we should consider specifying how to populate this member if no explicit id is provided by the tool in its non-SARIF output format. we could use a sentinel value that specifies it is unknown. it may be simpler to just make ruleId optional. 

this issue relates to a previously filed item on specifying a sentinel value for missing required data. we should review the spec to see what is, in fact, required, before making a call. at this point, there isn't much required data that must be provided by the tool.

**Comment by ghost** [comment]
Decision: Make it optional (SHOULD). Explain that tools "really" should emit it, but converters might not have anything available. Also explain that results of kind "note" don't need it.
