### ISSUE TITLE
Observations on version

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#98]
The CppCheck converter simply passes the XML-based version on to SARIF (which requires a semantic versioning 2.0 form). One example value is 1.66 but this value isn't valid according to the spec (it should be expressed as 1.66.0)

Do we want to continue to specify this format? The rationale for it is to allow for result mgmt. systems to perform some processing against a standard form, but I'm not sure what actual utility this has. The requirement places burdens on converters that must try to determine whether the provided tool version is in the right format (which would require library support) and then decide what to do to it to make it SV2.0 compatible. This breaks our principle of requiring converters to do as little transformation as possible.

I think I'd suggest that direct SARIF producers should prefer the semantic version 2.0 format but that converters should populate this value with whatever candidate data seems closest to that form. SARIF consumers can try to parse the version as SV 2.0 (if they have appropriate library support) but there's no guarantee.

**Comment by ghost** [comment]
@michaelcfanning Closing this. The spec now says that the version "should" be in Semantic Versioning format.
