### ISSUE TITLE
The SARIF version is not a semantic version 2.0 compatible version

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#99]
0.4 does not meet the spec, it should be 0.4.0. we shouldn't require an sv 2.0 version in toolInfo while providing a non sv 2.0 version ourselves. See issue #98.

**Comment by ghost** [comment]
Also mention that the SARIF version SHALL be in sv 2.0 format.

**Comment by ghost** [comment]
Fixed by ea454c8.
